addSbtPlugin("africa.shuwari" % "sbt-version" % "0.8.0")
addSbtPlugin("africa.shuwari" % "sbt-snx" % "0.3.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.6")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.1")
addSbtPlugin("com.github.sbt" % "sbt-header" % "5.11.0")
addSbtPlugin("africa.shuwari.sbt" % "sbt-shuwari-core" % "0.15.4")
addSbtPlugin("africa.shuwari.sbt" % "sbt-shuwari-scalac" % "0.15.4")
